#!/bin/sh

echo -n $0: 'Lexer operation... '

cat >test.ref <<'eof'
type 78
  10
type 128
type 78
  4
type 45
<10 print 4
>
eof

./test60 >test.data

if cmp test.ref test.data
then
  rm -f test.*
  echo passed
else
  echo failed
  exit 1
fi

