#!/bin/sh

echo -n $0: 'TIME and SLEEP... '

cat >test.bas <<'eof'
10 start=time
20 sleep 1
30 now=time
40 print now-start > 90 and now-start < 110
eof

cat >test.ref <<'eof'
-1 
eof

sh ./test/runbas test.bas >test.data

if cmp test.ref test.data
then
  rm -f test.*
  echo passed
else
  echo failed
  exit 1
fi

