#!/bin/sh

echo -n $0: 'FOR TO evaluation order... '

cat >test.bas <<'eof'
10 S=5
20 for S=1 to S+5
30   print S
40 next
eof

cat >test.ref <<'eof'
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 10 
eof

sh ./test/runbas test.bas >test.data

if cmp test.ref test.data
then
  rm -f test.*
  echo passed
else
  echo failed
  exit 1
fi

